/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingdemo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.table.*;
import javax.swing.*;
import javax.swing.event.*;
/**
 *
 * @author Cathy
 */
public class Customer extends javax.swing.JFrame {
    
    // DB connection
    private final String url = "jdbc:mysql://localhost:3306/maybank";
    private final String user = "root";
    private final String password = "P@ssw0rd888";
    private final String jdbcDriver = "com.mysql.cj.jdbc.Driver";

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        loadCustomer();
        //jTable2ComponentShown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer");
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setText("Customer List");

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Short Name", "Full Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(customerTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadCustomer(){
        System.out.println("List customer");
        
        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
        
        try {
            Class.forName(jdbcDriver);
            Connection connection = (Connection) DriverManager.getConnection(url, user, password);

            PreparedStatement statement = (PreparedStatement) connection
                .prepareStatement("select customerid, shortname, fullname from customer");

            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                System.out.println("ID = " + resultSet.getInt("customerid") + ", Short Name = " + resultSet.getString("shortname").trim()
                    + ", Full Name = " + resultSet.getString("fullname").trim());
                
                Object[] row = { resultSet.getInt("customerid"), resultSet.getString("shortname").trim(), resultSet.getString("fullname").trim() };

                model.addRow(row);
            }
            
            resultSet.close();
            statement.close();
            connection.close();

            ListSelectionModel listSelectionModel = customerTable.getSelectionModel();
            listSelectionModel.addListSelectionListener(new ListSelectionHandler());
            customerTable.setSelectionModel(listSelectionModel);
            
        } catch (Exception exception) {
            System.out.println(exception);
        }
    }
    
    
    
    class ListSelectionHandler implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            ListSelectionModel lsm = (ListSelectionModel) e.getSource();
            
            if(!lsm.isSelectionEmpty()) {
                int index = lsm.getMinSelectionIndex();
                System.out.println(customerTable.getValueAt(index, 0).toString());
                
                new Address(customerTable.getValueAt(index, 0).toString(), customerTable.getValueAt(index, 1).toString(), customerTable.getValueAt(index, 2).toString()).setVisible(true);
                
                setVisible(false);
                dispose();
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
